name: Daily Data Routine

on:
  schedule:
    - cron: '0 0 * * *' # รันทุกวันเวลา 00:00 UTC (07:00 น. เวลาไทย)
  workflow_dispatch: # เผื่อกรณีที่คุณต้องการกดรันเองผ่านหน้าเว็บ

jobs:
  run-routine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install requests PyJWT gspread google-auth python-dotenv -q

      - name: Create Credentials File on-the-fly
        run: echo '${{ secrets.GCP_CREDENTIALS_JSON }}' > credentials.json

      - name: Load Environment Variables
        run: echo "${{ secrets.ENV_FILE }}" >> $GITHUB_ENV

      - name: Execute Main Script
        run: |
          python cluster.py 
          rm credentials.json
